import Head from 'next/head'
import Header from './layout-components/Header'
import Footer from './layout-components/Footer'
// import styles from '../styles/components/Layout.module.css'

const Layout = ({ children, title }): JSX.Element => {
  return (
    <div>
      <Head>
        <title> Anantara Body Spa {title ? `- ${title}` : " "} </title>
        <meta name="description" content="Generated by create" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <main>
        {children}
      </main>
      <Footer />
    </div>
  )
}
export default Layout
