// import styles from '../styles/components/Layout.module.css'
import Head from 'next/head'
const Layout = ({ children, title }): JSX.Element => {
  return (
    <>
      <Head>
        <title> Anantara Body Spa {title ? `- ${title}` : ''} </title>
        <meta name="description" content="Generated by create" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>menu</div>
      <main>
        {children}
      </main>
      <div>footer</div>
    </>
  )
}

export default Layout
