// import Image from 'next/image'
import CardCategory from '../components/home/CardCategory'
import Head from '../node_modules/next/head'


export default function Home({ category }) {
  // console.log("categorias:", category)
  return (
    <div>
      <Head>
        <title>anantara body </title>
        <meta name="description" content="Generated by create" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1>
          Welcome anantara body spa
        </h1>
        <CardCategory category={category} />
      </main>
    </div>
  )
};

export function getStaticProps() {
  const data = require('../data.json')
  return {
    props: {
      category: data.categories
    }
  }
};
