// import Image from 'next/image'
import Head from '../node_modules/next/head'
import styles from '../styles/pages/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>anantara body </title>
        <meta name="description" content="Generated by create" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome anantara body spa
        </h1>
      </main>
    </div>
  )
}
