// import Image from 'next/image'
import Head from '../node_modules/next/head'
import styles from '../styles/pages/Home.module.css'

export default function Home({ category }) {
  // console.log("categorias:", category)
  return (
    <div className={styles.container}>
      <Head>
        <title>anantara body </title>
        <meta name="description" content="Generated by create" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome anantara body spa
        </h1>
      </main>
    </div>
  )
}
export function getStaticProps() {
  const data = require('../data.json')
  return {
    props: {
      category: data.categories
    }
  }
};
